---
bgp:
  asn: 65000
  router_id: 100.64.1.6
  neighbors:
    - ip: 100.64.1.1
      remote_asn: 65000
    - ip: 100.64.1.3
      remote_asn: 65000

interfaces:
  - name: GigabitEthernet2
    ip_address: 100.64.16.6
    subnet_mask: 255.255.255.0
    mpls_enabled: yes
  - name: GigabitEthernet3
    ip_address: 100.64.26.6
    subnet_mask: 255.255.255.0
    mpls_enabled: yes